main:
  - weight: 1
    identifier: home
    name: Anasayfa
    url: /
  - weight: 2
    identifier: about
    name: Hakkımda
    url: /hakkımda/
  - weight: 3
    identifier: photos
    name: Fotoğraflar
    url: https://www.flickr.com/photos/burakibis/
  - weight: 4
    identifier: roadmap
    name: Yol Haritası
    url: /yol-haritası/
  - weight: 5
    identifier: tags
    name: Etiketler
    url: /tags/
