title: buraste blog
description: Kişisel Blog
homeInfoParams:
  Title: Merhaba 👋 yaşadıklarıma dair bazı şeyler yazıyorum.
  Content:
    'Gün boyu online bir [spiritüel dükkanı](https://hellominaste.com) yönetiyorum.
    Geceleri micro service için yeminler edip sabah vazgeçiyorum 🪐 Benimle ilgili daha fazlası için 👉
    [tıkla](/tr/hakkimda)'
